# Generated by Django 6.0.2 on 2026-03-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='inserido_manualmente',
            field=models.BooleanField(default=False),
        ),
    ]
